#!/bin/bash
#
# Build the LB in a golang container
#
cd ..

docker build -t ndslabs/k8-ingress-nginx:builder - << DBUILD

FROM golang:1.6.2
WORKDIR /go/src
RUN go get github.com/tools/godep && go install github.com/tools/godep
RUN mkdir -p github.com/nds-org && cd github.com/nds-org && git clone https://github.com/nds-org/k8s-ingress-nginx.git
WORKDIR /go/src/github.com/nds-org/k8s-ingress-nginx
RUN godep restore
WORKDIR /go/src/github.com/nds-org/k8s-ingress-nginx/controllers/nginx/
RUN make
#RUN chmod a+x /usr/local/bin/build

CMD bash

DBUILD

